### ISSUE TITLE
My unofficial repo

### ISSUE THREAD

**Issue by notpeter** [pkolano/old-ballast-before-notpeter-merge#1]
Hey Paul,

I'm happy to see you've release ballast on Github.  You may not have known, but I actually put up an unofficial mirror a couple months back.  I even imported the old tarballs so my repo includes version history as well.

https://github.com/notpeter/nasa-ballast-ssh/

Since there's little reason for me to maintain my unofficial mirror now that you have an official one, I'd be happy to transfer ownership of that repository to you which mean your official repo would have the historic versions as well.

**Comment by pkolano** [comment]
hi Peter,

I did actually see that a little while back when I was randomly testing
various search terms.  I was going to send you a message that I had
finally put it on github but just hadn't gotten around to it yet.

I would be happy to take ownership, but I'm a git/github newbie so don't
really know how to best merge the two together to preserve the work
you've done importing the old versions.  If you have ideas on how this
can best be accomplished, please let me know.

thanks,

--Paul

**Comment by notpeter** [comment]
I've sent you the transfer request.  Once you accept all the git history, hashes and Issues (there's only two) will be identical. Any old links to my repo (notpeter/nasa-ballast-ssh) will automatically redirect to yours. You could then delete your existing repository ("ballast") and rename nasa-ballast-ssh to just 'ballast' (under the repo settings) and my redirect to pkolano/nasa-ballast-ssh would also correctly redirect to pkolano/ballast. 

Just so you know, I think the only deviation from your tarballs is my addition of a readme.md.  In the most recent release I renamed your new readme.md to README so as to not clobber my readme.md with the architecture diagram and other links.

Also since I set the git author on those commits to your NASA email address they currently aren't attributed to you ([for example this commit](https://github.com/notpeter/nasa-ballast-ssh/commit/a8409d1f9b4f5125ee8d0c52fedbd881a1741ab3) but if you [add your nasa email here](https://github.com/settings/emails) those commits will be associated with your github profile.

**Comment by notpeter** [comment]
Also, in case you're curious how imported the old history I just unpacked successive tarballs

**Comment by pkolano** [comment]
When I try the link, it says "Oops! That repository transfer has expired."

**Comment by notpeter** [comment]
That's super odd.  I've aborted and re-initiated the transfer request, perhaps it'll work now.

**Comment by notpeter** [comment]
Hey Paul,

Glad you were able to successfully accept my repo ownership request.

I would recommend you take pkolano/ballast (this repo) and rename to something else (pkolano/whatever) and then rename pkolano/temporary-notpeter-ballast to pkolano/ballast. Then once you've confirmed everything looks right, you can just delete pkolano/whatever. The only lost history would be this issue ;)

-Pete

**Comment by pkolano** [comment]
converted to main repo

**Comment by notpeter** [comment]
👍
